# -*- coding: utf-8 -*-
"""MarianMTModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2HEFF6k8egsC4HECjFe8Wg6tCKiYNGQ
"""

# Step 1: Install dependencies
!pip install transformers sentencepiece --quiet

# Simple Translation Example using Pretrained Model (MarianMT) in PyTorch
# ---------------------------------------------------------------

# Step 2: Import necessary libraries
from transformers import MarianMTModel, MarianTokenizer

# Step 3: Load Pretrained Translation Model
model_name = 'Helsinki-NLP/opus-mt-en-fr'  # English to French
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name)

# Step 4: Define Translation Function
def translate(texts):
    # Tokenize the input
    inputs = tokenizer(texts, return_tensors="pt", padding=True)
    # Generate translation output
    translated = model.generate(**inputs)
    # Decode the result
    return [tokenizer.decode(t, skip_special_tokens=True) for t in translated]

# Step 5: Provide English Sentences
english_sentences = [
    "I love artificial intelligence.",
    "How are you today?",
    "We are going to study Transformers in this class."
]

# Step 6: Translate to French
french_translations = translate(english_sentences)

# Step 7: Show Results
for en, fr in zip(english_sentences, french_translations):
    print(f"EN: {en}\nFR: {fr}\n")